#!/bin/bash

NAME="Python with Google Cloud SDK"
BASE_REPO=python
VARIANTS=

IMAGE_CUSTOMIZATIONS='
# Install google-cloud-sdk and kubectl, with a config volume
# cf. google/cloud-sdk
RUN apt-get install apt-transport-https lsb-release && \
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk kubectl

VOLUME ["/root/.config"]

# Add flake8
RUN pip install -U flake8
'

source ../shared/images/generate.sh
